############ options ####################

#generate_null_rule : yes
#comma_as_dead_span : yes
#use_mmap : yes
#remove_alignments: yes
# separate lm for lexical/normal fragment
#double_lm : yes

############ Rule Extraction ############

# source side with parsed dependency tree
# support format : stanford parser ( tag,base dependency )
file_source_tree : /poisson2/home2/raphael/ntcir10/data.full/data.en.tree
file_source_dep : /poisson2/home2/raphael/ntcir10/data.full/data.en.dep
# taget side with plain text
file_target : /poisson2/home2/raphael/ntcir10/data.full/data.ja
# aligment file
file_alignment : /poisson2/home2/raphael/ntcir10/data.full/aligned.grow-diag-final-and

# lexical probability table
file_lex_e2f : /poisson2/home2/raphael/ntcir10/data.full/lex.e2f
file_lex_f2e : /poisson2/home2/raphael/ntcir10/data.full/lex.f2e

# output file of rules extracted
rule_table_path : /poisson2/home2/raphael/ntcir10/gentile.full.model

# language model setting

#file_lm : /poisson2/home2/raphael/ntcir10/lm/ja.full.lm
file_lm : /home/raphael/ntcir10/lm/ja.full.binary
max_gram : 5

x_as_tag : no

max_merge_nodes : 3
max_tokens : 6
min_deep_extract_terminals : 3
max_transaction_rate : 3

############ Probability Estimate ############

# input file of rules_extracted

dispersion_tables : 10
max_rules_for_each_source: 2000

############ Decoder ############

debug : no

#input file of rule table is same as file_rules_final

#input translation data
file_translation_input_tree : /poisson2/home2/raphael/ntcir10/data.test.full/data.en.tree
file_translation_input_dep : /poisson2/home2/raphael/ntcir10/data.test.full/data.en.dep
# output translation data
file_translation_output : /poisson2/home2/raphael/ntcir10/data.test.full/gentile.full.ja

# the number of nbest in the mode of nbest output , make sure it bigger than 0;
nbest : 50

size_cube_pruning : 1000

size_beam : 1000

# max non-terminals in tree reconstruction
reconstruction_max_nt : 2

# weight settings
weights :
#- 0.000250277891921528
#- 0.112255466507067
#- 0.00304874515720193
#- 0.177728066800345
#- 0.119831671057158
#- -0.0379435315043803
#- -0.227536367484089
#- -0.017554329604174
#- 0.303851543993662
########################################
- 0.00596950305498102
- 0.0702448396785429
- 0.0544369594255997
- 0.135654037244263
- 0.157281527993101
- -0.0436228192716449
- -0.144734369757711
- -0.024341215018477
- 0.363714728555679
#######################################
#- -0.001419
#- 0.148405
#- 0.000533
#- 0.243370
#- 0.090815
#- -0.026167
#- -0.066947
#- -0.044390
#- 0.377953
