

############ Rule Extraction ############


# output file of rules extracted
rule_table_path : /poisson2/home2/raphael/ntcir10/gentile.full.model

# language model setting

file_lm : /poisson2/home2/raphael/ntcir10/lm/ja.full.binary
max_gram : 5

x_as_tag : no

max_merge_nodes : 3
max_tokens : 6
min_deep_extract_terminals : 3
max_transaction_rate : 3

############ Probability Estimate ############

# input file of rules_extracted

dispersion_tables : 10
max_rules_for_each_source: 2000

############ Decoder ############
debug : no

#input file of rule table is same as file_rules_final

#input translation data
file_translation_input_tree : /poisson2/home2/raphael/ntcir10/data.dev.full/data.en.tree
file_translation_input_dep : /poisson2/home2/raphael/ntcir10/data.dev.full/data.en.dep
# output translation data
file_translation_output : [PATH_OUTPUT]

# the number of nbest in the mode of nbest output , make sure it bigger than 0;
nbest : 50

size_cube_pruning : 1000

size_beam : 1000

# max non-terminals in tree reconstruction
reconstruction_max_nt : 2

# weight settings
weights :
[WEIGHTS]